---
title: "HousePrice(Kaggle)データ確認"
date: "`r Sys.Date()`"
author: 
output:
  rmdformats::readthedown:
  highlight: kate
  code_folding: hide
  self_contained: true
  thumbnails: false
  lightbox: false
  md_extensions: -ascii_identifiers
  css: styles_customized.css
---
  
```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
## Global options
options(max.print = "75")
opts_chunk$set(echo = FALSE,
               cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
```


***


# データの次元 (dim)
```{r, echo=T}
dim(dat)
```

***

# データのレコード数 (nrow)
```{r, echo=T}
nrow(dat)
```


***


# データのカラム数 (ncol)
```{r, echo=T}
ncol(dat)
```


***


# カラム名 (colnames)
```{r, echo=T}
colnames(dat)
```


# カラム名・データ型 (str)
```{r, echo=T}
str(dat)
```


***


## データサマリー情報

### 表示最大カテゴリ数
```{r results="asis", echo=T}
lstPrint[["nCategoryMax"]]
```

### データサンプル数 (再掲)
```{r results="asis", echo=F}
print(format(nrow(dat), big.mark=","), quote=F)
```

### データサマリー情報 (summaryInfo)
```{r results="asis", echo=F}
DT::datatable(lstPrint[["summaryInfo"]], extensions='ColReorder', options=list(dom='Rlfrtip', pageLength=20))
```

